### ISSUE TITLE
extra function

### ISSUE THREAD

**Issue by andersonbsp** [JellyBitz/xSROMap#3]
would it be possible to add the part to see the mob on the map? it would make it easier to identify where there are spots on the maps.

**Comment by JellyBitz** [comment]
My intentions is to keep the library as clean as possible for other usages.

Also, you can achieve that using "Script Editor" from [DEMO](https://jellybitz.github.io/xSROMap/) page.
Open "Script Editor", then copy and paste all the text from [this script](https://github.com/JellyBitz/xSROMap/files/8695894/xSROMap_Script_Monsters.zip) and click "Import".
You'll see markers from all spawn locations taken from vSRO database directly.

**Comment by andersonbsp** [comment]
thx man

Em dom., 15 de mai. de 2022 às 17:12, Engels Quintero <
***@***.***> escreveu:
