### ISSUE TITLE
What do you have inside Main.exe What is this trojan for Can you upload open source ?

### ISSUE THREAD

**Issue by ham1tcagdas** [JellyBitz/xSROMap#5]
![explorer_Oo4J4KbVFI](https://github.com/user-attachments/assets/2b0b0028-34ce-422a-a14b-9782a93ddeae)

**Comment by JellyBitz** [comment]
Look, this project is pretty old, you can find easier ways to extract all the data of NPCs directly from database nowadays.

Have you even read the steps?
It's up to you to download the executable or use and compile the code by yourself.

---
**2.)** Go to the following repository at **Repl.it**
> https://repl.it/@JellyBitz/xSROMap-Gen

.. and choose whatever option you think easier:
 
> **1.-** Download **main.exe**  
> **2.-** Locate the program at the folder with all mentioned required files  
> **3.-** Execute the program

> **1.-** Fork the repository  
> **2.-** Upload and replace the required files  
> **3.-** Click at RUN (green) button
